In [1]:
import numpy as np

In [5]:
x = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])#двумерный
print(x)
print(x[3][1])
print(x[:,1])
print(x.shape,)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[ 2  4  6  8 10]
(5, 2)


In [3]:
a= np.zeros(10)
b=np.ones(10)
c=np.full(10,5)
d=np.arange(10,20)
print(a,"\n",b,"\n",c,"\n",d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


In [7]:
arr=np.array([2,1,5,3,7,4,6,8])#сортировка
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


In [6]:
Z=np.random.random((10,10))
Zmin,Zmax,Zmean=Z.min(),Z.max(),Z.mean()#минимальный максимальный средний
print(Zmin,Zmax,Zmean)

0.03544141656564537 0.993083701463475 0.5291179568549339


In [8]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan - np.nan)
print(0.3==3*0.1)

nan
False
False
nan
False


In [10]:
d+b

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [11]:
d**c

array([ 100000,  161051,  248832,  371293,  537824,  759375, 1048576,
       1419857, 1889568, 2476099])

In [12]:
a.dtype

dtype('float64')